### PR TITLE
add login detail

### PR DESCRIPTION
**Pull request by 0guanhua0**
test:
login

### CODE REVIEW

**Comment by Voyz** [comment]
Hi @0guanhua0 thanks for the contribution.

Could you please add more explanation behind it? From what I understand, the suggestion you're adding is incorrect, but maybe I'm missing something.

**Comment by 0guanhua0** [comment]
no container, hint
```sh
guanhua@arch ~/ib (git)-[master] % sudo docker stop $(sudo docker ps -aq)
guanhua@arch ~/ib (git)-[master] % curl -X GET "https://localhost:5000/v1/api/one/user" -k
curl: (7) Failed to connect to localhost port 5000 after 0 ms: Couldn't connect to server
```

no login, no hint. silent success
```sh
guanhua@arch ~/ib (git)-[master] % sudo docker-compose up -d
guanhua@arch ~/ib (git)-[master] % curl -X GET "https://localhost:5000/v1/api/one/user" -k
guanhua@arch ~/ib (git)-[master] % echo $?
0
```

with login, cmd return account data

maybe we should add hint. silent success without output confuse me. if the design is to separate container start & login, then add this as hint
```sh
echo $?
```

**Comment by Voyz** [comment]
Thanks for expanding! I must admit I'm not entirely sure I'm still following you - sorry - so bear with me just a little longer.

The steps you describe in your addition - accessing localhost:5000 and inputting the credentials - is something that IBeam should do automatically for you. Hence my previous comment, that adding such lines to the README would be incorrect in this case. 

Are you trying to say that IBeam does not perform the authentication for you automatically, and you have to login manually?

Could you please share contents of your docker-compose (redacting any credentials) and the full output log of your container once started?

**Comment by 0guanhua0** [comment]
since container run in detach mode, no wonder no output
```sh
guanhua@arch ~/ib (git)-[master] % sudo docker-compose up -d
```

to check log
```sh
guanhua@arch ~/ib (git)-[master] % sudo docker compose logs -f
```

now with the log, i can verify. around 2 min for the auth process.
you are right on auto login. before no output so i just manual login, and this break other web api call.

**Comment by Voyz** [comment]
Ahh, great, I'm glad you've managed to figure it out 👍

**Pull request closed without merging**
