### PR TITLE
armv7 compatibility for docker image

### PR DESCRIPTION
**Pull request by matthewmoorcroft**
Added os libraries and installed Rust to be able to install cryptography python library required to make ibeam docker image compatible with armv7 architecture

### CODE REVIEW

**Comment by matthewmoorcroft** [comment]
My baa, it wasn't pillow, it was cryptography. Here is the [link](https://cryptography.io/en/3.4.2/installation.html#:~:text=installation%20will%20fail.-,You%20will%20also%20need%20to%20have%20Rust%20installed%20and%20available.,-If%20you%20need) to the docs with the requirement. Unsure why this hasn't caused issues without armv7 addition to docker build.

**Comment by matthewmoorcroft** [comment]
> So, do I understand correctly: manylinux installs Rust for us automatically, but is not available for armv7, hence you need to install it manually?
That is correct

> What are you trying to say here? Can you check how much each layer weighs in the new image and report it back here? Whether the addition is worth it would depend on how much build time and image weight it adds.

[This](https://hub.docker.com/layers/matthewmoorcroft/ibeam/0.6.1-rc4/images/sha256-40c04273f7b52e34cf874c3ed0021948fff99cfbf38c21d691d78185c8d98a28?context=explore) is one I built for armv7, it adds 300MB from Rust installation. In terms of build time below is the comparison between both.
arm64
arm7

**Comment by Voyz** [comment]
Thanks for the breakdown @matthewmoorcroft.

That's roughly a 50% increase in build time and image size. I think until there's a substantial userbase requesting it, I'd vote for this being an exceedingly large addition.

However, as to not throw your work away, how about we create a separate Dockerfile, eg. 'Dockerfile_armv7', in which we preserve these changes. It wouldn't become part of the main image, however it would make it available for other users who'd like to build for armv7. Would that make sense?

**Comment by matthewmoorcroft** [comment]
Hey @Voyz that makes perfect sense, will make changes to the code to create alternate versions.

**Comment by matthewmoorcroft** [comment]
Hey @Voyz sorry for the delay, created the two alternate versions for Docker, let me know if there are any other issues

**Comment by Voyz** [comment]
Hey @matthewmoorcroft no problem at all! Many thanks for picking this up once again and finishing this PR. Looks, great, ready to merge 👍

Thanks for this contribution!

**Review by Voyz — APPROVED** [review]

**Pull request merged**
